### ISSUE TITLE
Installation on a fresh Anaconda environment

### ISSUE THREAD

**Issue by sealhuang** [BNUCNL/FreeROI#126]
Anaconda is an ideal environment for common users as it provides an easily-used package management tool, the dependent packages of FreeROI can be installed easily in the env. Meanwhile, we should take care of the version of Qt, PyQt, and SIP, a mismatch of the package combination may cause unexpected program crash. Thus, a guideline or a script on specifying dependent package version is needed for new installation.

**Comment by sealhuang** [comment]
An usable package combination is qt 4.8.7, PyQt 4.11.4 and SIP 4.18.

**Comment by zuooonz** [comment]
Error when launch freeroi on ubuntu 16.04:

> Traceback (most recent call last):
  File "/home/z/anaconda2/bin/freeroi", line 25, in module
    from froi.main import BpMainWindow
  File "/usr/local/lib/python2.7/dist-packages/froi/main.py", line 16, in module
    from algorithm.tools import get_curr_hemi
  File "/usr/local/lib/python2.7/dist-packages/froi/algorithm/tools.py", line 3, in module
    from mayavi import mlab
ImportError: No module named mayavi


conda list :

> numpy           1.7.1 
scipy           0.13.2
nose            1.3.7
scikits-image   0.7.1
qt              4.8.7
pyqt            4.11.4
sip             4.18
nibabel         2.2.1
mayavi          4.5.0

**Comment by sealhuang** [comment]
@Youguang Have you config your anaconda settings (i.e. directory settings in bashrc) correctly? I think you still use the  the default python env in your system, not the Anaconda.

**Comment by zuooonz** [comment]
When run `which python`, it returns:

> /home/z/anaconda2/bin/python

I am a newbie, is this right?

**Comment by sealhuang** [comment]
It seems that the anaconda python has been set as the default. However, from the error trackback, i find you might install freeroi using the system default python. If you install freeroi with anaconda python, the code of freeroi would stored in the dir, like 'home/z/anaconda2/lib/python2.7/dist-packages/froi'.
Thus, 1) you can check the `/usr/bin/env python` settings using the command `type -a python`, 2) Can you import mayavi in the anaconda python env?

**Comment by zuooonz** [comment]
`type -a python` returned:

> type -a python
python is /home/z/anaconda2/bin/python
python is /home/z/anaconda2/bin/python
python is /usr/bin/python

Mayavi could be imported by the simple py script: 

`import mayavi`

But when importing mlab by  this script: 

`from mayavi import mlab`

it showed: 

> GLib-GIO-Message: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
RuntimeError: module compiled against API version 0xa but this version of numpy is 0x7
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    from mayavi import mlab
  File "/home/z/anaconda2/lib/python2.7/site-packages/mayavi/mlab.py", line 27, in <module>
    from mayavi.tools.camera import view, roll, yaw, pitch, move
  File "/home/z/anaconda2/lib/python2.7/site-packages/mayavi/tools/camera.py", line 25, in <module>
    from .engine_manager import get_engine
  File "/home/z/anaconda2/lib/python2.7/site-packages/mayavi/tools/engine_manager.py", line 14, in <module>
    from mayavi.core.engine import Engine
  File "/home/z/anaconda2/lib/python2.7/site-packages/mayavi/core/engine.py", line 28, in <module>
    from mayavi.core.base import Base
  File "/home/z/anaconda2/lib/python2.7/site-packages/mayavi/core/base.py", line 19, in <module>
    from tvtk.pyface.tvtk_scene import TVTKScene
  File "/home/z/anaconda2/lib/python2.7/site-packages/tvtk/pyface/tvtk_scene.py", line 28, in <module>
    from tvtk.pyface import light_manager
  File "/home/z/anaconda2/lib/python2.7/site-packages/tvtk/pyface/light_manager.py", line 130, in <module>
    class CameraLight(HasTraits):
  File "/home/z/anaconda2/lib/python2.7/site-packages/tvtk/pyface/light_manager.py", line 146, in CameraLight
    source = Instance(tvtk.Light, ())
  File "/home/z/anaconda2/lib/python2.7/site-packages/tvtk/tvtk_classes.zip/tvtk_classes/tvtk_helper.py", line 225, in <lambda>
  File "/home/z/anaconda2/lib/python2.7/site-packages/tvtk/tvtk_classes.zip/tvtk_classes/tvtk_helper.py", line 36, in get_class
  File "/home/z/anaconda2/lib/python2.7/site-packages/tvtk/tvtk_classes.zip/tvtk_classes/tvtk_helper.py", line 28, in get_module
  File "/home/z/anaconda2/lib/python2.7/site-packages/tvtk/tvtk_classes.zip/tvtk_classes/light.py", line 12, in <module>
  File "/home/z/anaconda2/lib/python2.7/site-packages/tvtk/array_handler.py", line 28, in <module>
    from tvtk.array_ext import set_id_type_array
ImportError: numpy.core.multiarray failed to import

**Comment by sunshineDrizzle** [comment]
@Youguang Hi, would you mind providing outputs of the codes below for us?
You can get the outputs by execute these codes on a terminal:
1. `echo $PYTHONPATH`
2. `ipython`
        In[1]: import sys
        In[2]: sys.path

**Comment by zuooonz** [comment]
`echo $PYTHONPATH`

no output !!

`sys.path`

>  ['',
 '/home/z/anaconda2/bin',
 '/home/z/anaconda2/lib/python27.zip',
 '/home/z/anaconda2/lib/python2.7',
 '/home/z/anaconda2/lib/python2.7/plat-linux2',
 '/home/z/anaconda2/lib/python2.7/lib-tk',
 '/home/z/anaconda2/lib/python2.7/lib-old',
 '/home/z/anaconda2/lib/python2.7/lib-dynload',
 '/home/z/.local/lib/python2.7/site-packages',
 '/home/z/anaconda2/lib/python2.7/site-packages',
 '/home/z/anaconda2/lib/python2.7/site-packages/IPython/extensions',
 '/home/z/.ipython']

**Comment by sunshineDrizzle** [comment]
@Youguang How about outputs of these codes?

1. `ls /home/z/.local/lib/python2.7/site-packages`
2. `ls /usr/local/lib/python2.7/dist-packages`
3. `python -c "import sys,pprint;pprint.pprint(sys.path)"`
4. `/usr/bin/env python`

**Comment by zuooonz** [comment]
`ls /home/z/.local/lib/python2.7/site-packages`

> Cython			 cython.pyc	   pip			pyximport
> Cython-0.27.3.dist-info  easy_install.py   pip-9.0.1.dist-info	setuptools
> cython.py		 easy_install.pyc  pkg_resources	setuptools-38.2.5.dist-info

`ls /usr/local/lib/python2.7/dist-packages`

> apptools				     pylab.py
> apptools-4.4.0.dist-info		     pylab.pyc
> backports				     pyparsing-2.2.0.dist-info
> backports.functools_lru_cache-1.4.dist-info  pyparsing.py
> configobj-5.0.6.dist-info		     pyparsing.pyc
> configobj.py				     python_dateutil-2.6.1.dist-info
> configobj.pyc				     pytz
> cycler-0.10.0.dist-info			     pytz-2017.3.dist-info
> cycler.py				     PyWavelets-0.5.2.dist-info
> cycler.pyc				     pywt
> dateutil				     scikit_image-0.13.1.dist-info
> decorator-4.1.2.dist-info		     scikit_learn-0.19.1.dist-info
> decorator.py				     scipy
> decorator.pyc				     scipy-1.0.0.dist-info
> freeroi-0.2.3.beta.egg-info		     six-1.11.0.dist-info
> froi					     six.py
> matplotlib				     six.pyc
> matplotlib-2.1.1.dist-info		     skimage
> matplotlib-2.1.1-py2.7-nspkg.pth	     sklearn
> mpl_toolkits				     subprocess32-3.2.7-py2.7.egg-info
> networkx				     subprocess32.py
> networkx-2.0-py2.7.egg-info		     subprocess32.pyc
> nibabel					     traits
> nibabel-2.2.1.dist-info			     traits-4.6.0.dist-info
> nisext					     traitsui
> numpy					     traitsui-5.1.0.dist-info
> numpy-1.14.0.dist-info			     validate.py
> PIL					     validate.pyc
> Pillow-5.0.0.dist-info			     _version.py
> _posixsubprocess.so			     _version.pyc
> pyface					     virtualenv-15.1.0.dist-info
> pyface-5.1.0.dist-info			     virtualenv.py
> pygments				     virtualenv.pyc
> Pygments-2.2.0.dist-info		     virtualenv_support

`python -c "import sys,pprint;pprint.pprint(sys.path)"`

> ['',
>  '/home/z/anaconda2/lib/python27.zip',
>  '/home/z/anaconda2/lib/python2.7',
>  '/home/z/anaconda2/lib/python2.7/plat-linux2',
>  '/home/z/anaconda2/lib/python2.7/lib-tk',
>  '/home/z/anaconda2/lib/python2.7/lib-old',
>  '/home/z/anaconda2/lib/python2.7/lib-dynload',
>  '/home/z/.local/lib/python2.7/site-packages',
>  '/home/z/anaconda2/lib/python2.7/site-packages']

`/usr/bin/env python`

> Python 2.7.14 |Anaconda custom (64-bit)| (default, Oct 16 2017, 17:29:19) 
> [GCC 7.2.0] on linux2
> Type "help", "copyright", "credits" or "license" for more information.
> >>>

**Comment by sunshineDrizzle** [comment]
@Youguang It seems that these outputs are normal. I think you can try `python setup.py install` again.

**Comment by zuooonz** [comment]
After ran `python setup.py install ` ran `freeroi` : 

> Traceback (most recent call last):
>   File "/home/z/anaconda2/bin/freeroi", line 25, in <module>
>     from froi.main import BpMainWindow
>   File "/usr/local/lib/python2.7/dist-packages/froi/main.py", line 16, in <module>
>     from algorithm.tools import get_curr_hemi
>   File "/usr/local/lib/python2.7/dist-packages/froi/algorithm/tools.py", line 3, in <module>
>     from mayavi import mlab
> ImportError: No module named mayavi

**Comment by sealhuang** [comment]
Hi, @Youguang Please forgive my verbosity.
I think you need to reinstall freeroi under the anaconda env.
Please follow the procedure:
1) remove current installed froi directory.
`cd /usr/local/lib/python2.7/dist-packages/`
`rm -rf froi`
2) assert the default python interpreter is the Anaconda one
`cd ~`
`which python`
the output should be /home/z/anaconda2/bin/python
3) Next reinstall freeroi by enter into the freeroi source code and run
`python setup.py install`
And the `froi` dir should be installed in `/home/z/anaconda2/lib/python2.7/site-packages`.
4) run freeroi script

**Comment by zuooonz** [comment]
I have done as you said, then ran `freeroi`

> Traceback (most recent call last):
>   File "/home/z/anaconda2/bin/freeroi", line 24, in <module>
>     from froi import utils as froi_utils
> ImportError: No module named froi

**Comment by sealhuang** [comment]
Can you find the froi dir in the `/home/z/anaconda2/lib/python2.7/site-packages`?

**Comment by zuooonz** [comment]
yes, contents in froi:

> algorithm
> colormap.py
> colormap.pyc
> core
> data
> icon
> __init__.py
> __init__.pyc
> interface
> io
> main.py
> main.pyc
> utils.py
> utils.pyc
> version.py
> version.pyc
> widgets
>

**Comment by sunshineDrizzle** [comment]
@Youguang Where did you run the `freeroi`? On a terminal or an IDE?
If you want to run it on an IDE (such as PyCharm), please make sure that the interpreter is /home/z/anaconda2/bin/python.

**Comment by zuooonz** [comment]
I ran `freeroi` in TCSH and BASH.

**Comment by sealhuang** [comment]
Hi, @Youguang sorry for the late reply.
The problem is a bit weird. can you help us to find the root cause of problem?
If yes, please copy the following code into a new text file (i.e. test.py) in your home dir, and change the file mode to 755, next please run the script with `./test.py` and show us the output.

Code (Note: please replace the `____` with 4 blank)

#! /usr/bin/env python
import os
import sys
print 'PYTHONPATH list:'
for item in sys.path:
____print item
print 'PYTHONPATH in shell env:
for item in os.environ['PYTHONPATH']:
____print item

**Comment by zuooonz** [comment]
>   File "./test.py", line 7
>     print 'PYTHONPATH in shell env:
>                                                        ^
> SyntaxError: EOL while scanning string literal

**Comment by sealhuang** [comment]
@Youguang Sorry... replace this line as 
print 'PYTHONPATH in shell env:'

**Comment by zuooonz** [comment]
> PYTHONPATH list:
> /home/z
> /home/z/anaconda2/lib/python27.zip
> /home/z/anaconda2/lib/python2.7
> /home/z/anaconda2/lib/python2.7/plat-linux2
> /home/z/anaconda2/lib/python2.7/lib-tk
> /home/z/anaconda2/lib/python2.7/lib-old
> /home/z/anaconda2/lib/python2.7/lib-dynload
> /home/z/.local/lib/python2.7/site-packages
> /home/z/anaconda2/lib/python2.7/site-packages
> PYTHONPATH in shell env:
> Traceback (most recent call last):
>   File "./test.py", line 8, in <module>
>     for item in os.environ['PYTHONPATH']:
>   File "/home/z/anaconda2/lib/python2.7/UserDict.py", line 40, in __getitem__
>     raise KeyError(key)
> KeyError: 'PYTHONPATH'

**Comment by sealhuang** [comment]
Hi @Youguang  I recommend you remove the `lib` files in your home directory by following command
rm -rf ~/.local. And next, please remove the froi files (i.e. rm -rf /home/z/anaconda2/lib/python2.7/site-packages/froi), and reinstall the freeroi. If you encounter the error like `ImportError: No module named XXX`, please use `conda install XXX` to install the package XXX.

**Comment by zuooonz** [comment]
There are many files in .local, what is the effect to other software of removing .local ?

> bin:
> cygdb
> cython
> cythonize
> easy_install
> easy_install-2.7
> pip
> pip2
> pip2.7
> 
> lib:
> python2.7
> 
> share:
> applications
> data
> desktop-directories
> eog-wallpaper.tiff
> evolution
> gegl-0.3
> gnome-software
> grilo-plugins
> gsettings-data-convert
> gstreamer-1.0
> gvfs-metadata
> icc
> icons
> keyrings
> mime
> nautilus
> previews
> recently-used.xbel
> rhythmbox
> session_migration-(null)
> session_migration-ubuntu
> shotwell
> sounds
> totem
> Trash
> unity-settings-daemon
> vlc
> webkitgtk
> zeitgeist

**Comment by sealhuang** [comment]
The `~/.local` directory contains your user-local installed python packages, it is created by your 'pip install XXX' command (the pip is not in the anaconda env). These packages are not necessary for the system.

**Comment by zuooonz** [comment]
Report the same error after reinstall:

> Traceback (most recent call last):
>   File "/home/z/anaconda2/bin/freeroi", line 24, in <module>
>     from froi import utils as froi_utils
> ImportError: No module named froi

**Comment by sealhuang** [comment]
Hi, @Youguang Please run the `test.py` again, and check if the dir `froi` is installed in the dir `/home/z/anaconda2/lib/python2.7/site-packages`

**Comment by sealhuang** [comment]
Hi @Youguang I think I find the root cause of problem you encountered.
A file in your `froi` dir may be renamed abnormally.
Please check the contents of the `init.py` in your `froi` dir, normally, this file should be named as `__init__.py`, you can renamed this file manually, and run freeroi for testing.

**Comment by zuooonz** [comment]
> PYTHONPATH list:
> /home/z
> /home/z/anaconda2/lib/python27.zip
> /home/z/anaconda2/lib/python2.7
> /home/z/anaconda2/lib/python2.7/plat-linux2
> /home/z/anaconda2/lib/python2.7/lib-tk
> /home/z/anaconda2/lib/python2.7/lib-old
> /home/z/anaconda2/lib/python2.7/lib-dynload
> /home/z/.local/lib/python2.7/site-packages
> /home/z/anaconda2/lib/python2.7/site-packages
> PYTHONPATH in shell env:
> Traceback (most recent call last):
>   File "./test.py", line 8, in <module>
>     for item in os.environ['PYTHONPATH']:
>   File "/home/z/anaconda2/lib/python2.7/UserDict.py", line 40, in __getitem__
>     raise KeyError(key)
> KeyError: 'PYTHONPATH'

**Comment by sealhuang** [comment]
@Youguang 
sad...If you don't mind, we may try to solve the problem via some kinds of IM software....

**Comment by zuooonz** [comment]
@sealhuang 
Thank you， it has been successfully installed.
